# Generated by Django 3.1.4 on 2020-12-08 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, verbose_name='项目名')),
                ('project_desc', models.CharField(blank=True, max_length=200, verbose_name='项目描述')),
                ('status', models.BooleanField(verbose_name='状态')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_user', models.CharField(max_length=30)),
                ('addr', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
            ],
            options={
                'verbose_name': '测试使用',
                'verbose_name_plural': '测试使用',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Modules_name', models.CharField(max_length=20, verbose_name='模块名')),
                ('Developer', models.CharField(blank=True, max_length=100, verbose_name='开发人员')),
                ('Modules_desc', models.CharField(blank=True, max_length=200, verbose_name='模块描述')),
                ('status', models.BooleanField(verbose_name='状态')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='functional_test.project', verbose_name='项目名')),
                ('Testers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='测试人员')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
    ]
